### ISSUE TITLE
PLC is not a constructor

### ISSUE THREAD

**Issue by AlonsoGuerrero** [punisher97/node-logix#2]
When I try to run the **Example with events, read and write tags** the console prints TypeError: PLC is not a constructor

**Comment by punisher97** [comment]
Hi, sorry its my mistake, you should import using 'default':
Eg:
```
const PLC = require("node-logix").default;
```
Check others examples: https://github.com/punisher97/node-logix/blob/master/examples/01_write_read_simple.js
